name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script on EC2
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/app
          
            # GitHub Secrets에서 주입한 값들을 EC2 환경 변수로 설정합니다.
            export DB_URL="${{ secrets.DB_URL }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export GITHUB_CLIENT_ID="${{ secrets.GH_CLIENT_ID }}"
            export GITHUB_CLIENT_SECRET="${{ secrets.GH_CLIENT_SECRET }}"
            export REDIS_HOST="${{ secrets.REDIS_HOST }}"
            export REDIS_PW="${{ secrets.REDIS_PW }}"
          
            git fetch origin main
            git reset --hard origin/main
            ./deploy.sh
          EOF
